const API='/api';let token=localStorage.getItem('arcanum_token')||'',user=JSON.parse(localStorage.getItem('arcanum_user')||'null'),articles=[],sources=[],editingId=null,pdfURL=null,zoom=1,currentFileId=null;
const glossaryData=[['Sigil','Biểu tượng được thiết kế/ghi nhận trong nhiều hệ thống huyền thuật.'],['Grimoire','Thuật ngữ thường dùng cho sách hoặc bản thảo về phép thuật/nghi thức.'],['Correspondence','Hệ thống liên hệ biểu tượng giữa vật thể, màu sắc, hành tinh, thảo dược…'],['Hermeticism','Truyền thống tư tưởng gắn với Corpus Hermeticum và Hermes Trismegistus.'],['Divination','Các phương pháp diễn giải dấu hiệu nhằm tìm hiểu câu hỏi hoặc hoàn cảnh.']];
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));function toast(s){const e=$('toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
async function api(path,opts={}){const h={'Content-Type':'application/json',...(opts.headers||{})};if(token)h.Authorization='Bearer '+token;const r=await fetch(API+path,{...opts,headers:h});if(r.status===401){token='';user=null;localStorage.removeItem('arcanum_token');localStorage.removeItem('arcanum_user')}let d=null;try{d=await r.json()}catch{}if(!r.ok)throw Error(d?.error||`HTTP ${r.status}`);return d}
async function uploadFile(file){const fd=new FormData();fd.append('file',file);const h=token?{Authorization:'Bearer '+token}:{};const r=await fetch(API+'/files',{method:'POST',headers:h,body:fd}),d=await r.json().catch(()=>null);if(!r.ok)throw Error(d?.error||'Không thể tải tệp');return d}
async function loadArticles(){const p=new URLSearchParams(),q=(($('mainSearch')?.value||'')+' '+($('quickSearch')?.value||'')).trim();if(q)p.set('q',q);if($('categoryFilter')?.value)p.set('category',$('categoryFilter').value);if($('formatFilter')?.value)p.set('format',$('formatFilter').value);articles=await api('/articles?'+p);renderArchive()}
async function loadSources(){if(!token){sources=[];renderSources();return}sources=await api('/files');renderSources();renderStats()}
function route(n){document.querySelectorAll('.route').forEach(x=>x.classList.remove('active'));$(n)?.classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.route===n));location.hash=n;if(n==='home')loadArticles().catch(handleError);if(n==='contribute')renderMyArticles();if(n==='sources'){loadSources().catch(handleError);renderGlossary()}}
function setupNav(){document.querySelectorAll('[data-route]').forEach(x=>x.addEventListener('click',e=>{e.preventDefault();route(x.dataset.route)}));window.addEventListener('hashchange',()=>{const r=location.hash.slice(1);if(['home','contribute','sources','about'].includes(r))route(r)})}
function handleError(e){console.error(e);toast(e.message||'Có lỗi kết nối');if(!token&&/401|Unauthorized/i.test(e.message))openAuth()}
function renderArchive(){const q=(($('mainSearch')?.value||'')+' '+($('quickSearch')?.value||'')).trim().toLowerCase(),c=$('categoryFilter').value,f=$('formatFilter').value,s=$('sortFilter').value;let a=articles.filter(x=>(!q||JSON.stringify(x).toLowerCase().includes(q))&&(!c||x.category===c)&&(!f||x.format===f));a.sort((x,y)=>s==='popular'?y.views-x.views:s==='saved'?y.saved-x.saved:new Date(y.updated_at)-new Date(x.updated_at));$('archiveGrid').innerHTML=a.length?a.map(card).join(''):'<div class="empty">Không có tài liệu phù hợp.</div>';renderStats();renderPopular();hydrateImages()}
function card(x){return `<article class="card"><div class="thumb">${x.cover_file_id?`<img data-cover-id="${x.cover_file_id}" alt="">`:'✦'}</div><div class="card-body"><span class="tag">${esc(x.category)}</span><h3>${esc(x.title)}</h3><div class="snippet">${esc(x.snippet||x.body?.slice(0,140)||'')}</div><div class="card-meta"><span>${esc(x.author||'Arcanum')} · ${Math.max(1,Math.ceil((x.body||'').length/1000))} phút</span><button class="bookmark" data-bookmark="${x.id}">☆ ${x.saved||0}</button></div></div></article>`}
async function hydrateImages(root=document){for(const img of root.querySelectorAll('[data-cover-id]'))try{const r=await fetch(API+'/files/'+img.dataset.coverId,{headers:token?{Authorization:'Bearer '+token}:{}});if(r.ok)img.src=URL.createObjectURL(await r.blob())}catch{} }
function renderStats(){$('statArticles').textContent=articles.length;$('statSources').textContent=sources.length;$('statBookmarks').textContent=articles.reduce((n,x)=>n+(x.saved||0),0)}function renderPopular(){$('popularList').innerHTML=articles.slice().sort((a,b)=>(b.views||0)-(a.views||0)).slice(0,5).map(x=>`<li>${esc(x.title)}</li>`).join('')||'<li>Chưa có dữ liệu</li>'}
async function bookmark(id){if(!token){openAuth();return}try{await api('/articles/'+id+'/bookmark',{method:'POST'});await loadArticles();toast('Đã lưu bài viết')}catch(e){handleError(e)}}function clearFilters(){$('mainSearch').value='';$('quickSearch').value='';$('categoryFilter').value='';$('formatFilter').value='';loadArticles().catch(handleError)}
function resetEditor(){editingId=null;['articleTitle','articleTags','articleBody','articleCitations'].forEach(i=>$(i).value='');$('articleAuthor').value=user?.display_name||'Thành viên';$('articleVisibility').value='Công khai';$('articleFormat').value='Bài viết';$('coverFile').value='';$('articlePreview').textContent='Bản xem trước sẽ xuất hiện ở đây.';$('versionInfo').textContent='Bài viết mới chưa có phiên bản.'}
function markdownToHTML(s){let h=esc(s);h=h.replace(/^### (.*)$/gm,'<h4>$1</h4>').replace(/^## (.*)$/gm,'<h3>$1</h3>').replace(/^# (.*)$/gm,'<h2>$1</h2>').replace(/^> (.*)$/gm,'<blockquote>$1</blockquote>').replace(/^- (.*)$/gm,'<li>$1</li>').replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\*(.*?)\*/g,'<em>$1</em>').replace(/\n\n/g,'</p><p>').replace(/\n/g,'<br>');return '<p>'+h+'</p>'}function preview(){const t=$('articleTitle').value||'Chưa có tiêu đề';$('articlePreview').innerHTML=`<h2>${esc(t)}</h2>${markdownToHTML($('articleBody').value||'')}`}
async function saveArticle(publish){if(!token){openAuth();return}const title=$('articleTitle').value.trim();if(!title){toast('Hãy nhập tiêu đề');return}const old=editingId?articles.find(x=>x.id===editingId):null;try{let coverFileId=old?.cover_file_id||null;const file=$('coverFile').files[0];if(file)coverFileId=(await uploadFile(file)).id;const body=$('articleBody').value,payload={title,category:$('articleCategory').value,format:$('articleFormat').value,visibility:$('articleVisibility').value,tags:$('articleTags').value.split(',').map(x=>x.trim().replace(/^#/,'')).filter(Boolean),body,citations:$('articleCitations').value,snippet:body.replace(/[#>*_-]/g,'').trim().slice(0,170),status:publish?'published':'draft',coverFileId};const obj=old?await api('/articles/'+old.id,{method:'PUT',body:JSON.stringify(payload)}):await api('/articles',{method:'POST',body:JSON.stringify(payload)});editingId=obj.id;await loadArticles();renderMyArticles();$('versionInfo').textContent=`Phiên bản ${obj.version||1} · ${publish?'Đã xuất bản':'Bản nháp'}`;toast(publish?'Đã đăng tải lên kho chung':'Đã lưu nháp trên máy chủ')}catch(e){handleError(e)}}
function renderMyArticles(){$('myArticles').innerHTML=articles.slice().sort((a,b)=>new Date(b.updated_at)-new Date(a.updated_at)).map(x=>`<div class="draft-row"><span><b>${esc(x.title)}</b><small class="muted"> · ${esc(x.status||'published')} · v${x.version||1}</small></span><button class="draft-btn" data-edit="${x.id}">Sửa</button></div>`).join('')||'<div class="empty">Chưa có bài.</div>'}
function editArticle(id){const x=articles.find(a=>a.id==id);if(!x)return;editingId=x.id;$('articleTitle').value=x.title;$('articleCategory').value=x.category;$('articleFormat').value=x.format;$('articleTags').value=(x.tags||[]).map(t=>'#'+t).join(', ');$('articleBody').value=x.body||'';$('articleCitations').value=x.citations||'';$('articleVisibility').value=x.visibility||'Công khai';$('articleAuthor').value=x.author||user?.display_name||'Thành viên';$('versionInfo').textContent=`Phiên bản ${x.version||1} · ${x.status||'published'}`;preview();route('contribute')}
function renderGlossary(filter=''){const q=filter.toLowerCase();$('glossary').innerHTML=glossaryData.filter(x=>!q||x[0].toLowerCase().includes(q)||x[1].toLowerCase().includes(q)).map(x=>`<div class="term"><b>${esc(x[0])}</b><div class="muted">${esc(x[1])}</div></div>`).join('')}
function renderSources(){$('sourceLibrary').innerHTML=sources.length?sources.map(x=>`<div class="source-row"><span><b>${esc(x.name)}</b><small class="muted"> · ${new Date(x.created_at).toLocaleDateString('vi-VN')} · PDF/Ảnh online</small></span><button data-open-source="${x.id}">Mở</button></div>`).join(''):'<div class="empty">Chưa có nguồn PDF/ảnh trên tài khoản.</div>'}
async function openPDF(file,recordId=null){if(!token){openAuth();return}try{let id=recordId;if(file){const f=await uploadFile(file);id=f.id}if(!id)return;const r=await fetch(API+'/files/'+id,{headers:{Authorization:'Bearer '+token}}),b=await r.blob();if(pdfURL)URL.revokeObjectURL(pdfURL);pdfURL=URL.createObjectURL(b);$('pdfStage').innerHTML=`<iframe src="${pdfURL}#zoom=${Math.round(zoom*100)}"></iframe>`;$('pageLabel').textContent='Trang —';currentFileId=id;toast('Đã mở tệp online')}catch(e){handleError(e)}}
async function saveTranslation(){if(!token){openAuth();return}if(!currentFileId){toast('Hãy mở một PDF trước');return}try{const progress=Math.min(100,Math.max(0,parseInt($('progressText').dataset.value||'0')));await api('/translations',{method:'POST',body:JSON.stringify({sourceFileId:currentFileId,chapter:'',sourceText:$('sourceSelection').value,translatedText:$('translationText').value,notes:$('translationNotes').value,progress})});toast('Đã đồng bộ tiến độ dịch')}catch(e){handleError(e)}}
function autoTranslate(){const t=$('sourceSelection').value.trim();if(!t){toast('Nhập đoạn gốc trước');return}$('translationText').value='BẢN NHÁP DỊCH — cần kết nối dịch vụ AI để dịch tự động.\n\n'+t;toast('Đã tạo bản nháp')}
async function sendFeedback(){if(!$('contactMessage').value.trim()){toast('Hãy nhập nội dung');return}try{await api('/feedback',{method:'POST',body:JSON.stringify({name:$('contactName').value,email:$('contactEmail').value,message:$('contactMessage').value})});toast('Đã gửi phản hồi lên máy chủ')}catch(e){handleError(e)}}
function openAuth(){$('modalBody').innerHTML='<div class="auth-box"><h2>Đăng nhập Arcanum</h2><input id="authEmail" type="email" placeholder="Email"><input id="authPassword" type="password" placeholder="Mật khẩu (tối thiểu 8 ký tự)"><input id="authName" placeholder="Tên hiển thị (khi đăng ký)"><div class="auth-actions"><button id="loginNow">Đăng nhập</button><button id="registerNow">Tạo tài khoản</button></div><p class="muted">Tài khoản được lưu trên máy chủ Arcanum.</p></div>';$('modal').classList.remove('hidden');$('loginNow').onclick=()=>doAuth(false);$('registerNow').onclick=()=>doAuth(true)}
async function doAuth(register){try{const d=await api(register?'/auth/register':'/auth/login',{method:'POST',body:JSON.stringify({email:$('authEmail').value.trim(),password:$('authPassword').value,displayName:$('authName').value.trim()})});token=d.token;user=d.user;localStorage.setItem('arcanum_token',token);localStorage.setItem('arcanum_user',JSON.stringify(user));$('modal').classList.add('hidden');updateAuthUI();await loadArticles();await loadSources();toast(register?'Tạo tài khoản thành công':'Đăng nhập thành công')}catch(e){toast(e.message)}}
function updateAuthUI(){$('authBtn').textContent=user?`Hồ sơ · ${user.display_name}`:'Đăng nhập';$('storageStatus').textContent=user?`Cloud PostgreSQL · ${user.role}`:'Chưa đăng nhập · kho chung chỉ đọc'}function authClick(){if(user){$('modalBody').innerHTML=`<h2>${esc(user.display_name)}</h2><p>${esc(user.email)}</p><p>Vai trò: <b>${esc(user.role)}</b></p><button id="logoutNow">Đăng xuất</button>`;$('modal').classList.remove('hidden');$('logoutNow').onclick=()=>{token='';user=null;localStorage.clear();$('modal').classList.add('hidden');updateAuthUI();loadArticles();loadSources()}}else openAuth()}
function lunar(){const syn=29.530588853,ref=Date.UTC(2000,0,6,18,14),age=((Date.now()-ref)/86400000%syn+syn)%syn,n=[['Trăng non','●'],['Lưỡi liềm đầu tháng','◒'],['Thượng huyền','◐'],['Trăng khuyết đầu tháng','◓'],['Trăng tròn','○'],['Trăng khuyết cuối tháng','◓'],['Hạ huyền','◑'],['Lưỡi liềm cuối tháng','◒']],i=Math.floor(age/syn*8)%8;$('moonName').textContent=n[i][0];$('moonIcon').textContent=n[i][1];$('moonInfo').textContent=`Tuổi trăng xấp xỉ ${age.toFixed(1)} ngày. Dùng lịch thiên văn chuyên dụng khi cần độ chính xác cao.`}
function setup(){setupNav();['mainSearch','quickSearch'].forEach(id=>$(id).addEventListener('input',()=>loadArticles().catch(handleError)));['categoryFilter','formatFilter','sortFilter'].forEach(id=>$(id).addEventListener('change',()=>loadArticles().catch(handleError)));$('clearFilters').onclick=clearFilters;$('newArticle').onclick=resetEditor;$('saveDraft').onclick=()=>saveArticle(false);$('publishArticle').onclick=()=>saveArticle(true);$('previewArticle').onclick=preview;document.querySelectorAll('[data-md]').forEach(b=>b.onclick=()=>{const ta=$('articleBody'),m=b.dataset.md,pos=ta.selectionStart;ta.value=ta.value.slice(0,pos)+m+ta.value.slice(ta.selectionEnd);ta.focus()});$('archiveGrid').addEventListener('click',e=>{const b=e.target.closest('[data-bookmark]');if(b)bookmark(b.dataset.bookmark)});$('myArticles').addEventListener('click',e=>{if(e.target.dataset.edit)editArticle(e.target.dataset.edit)});$('pdfFile').onchange=e=>openPDF(e.target.files[0]);$('dropZone').ondragover=e=>e.preventDefault();$('dropZone').ondrop=e=>{e.preventDefault();openPDF(e.dataTransfer.files[0])};$('translateBtn').onclick=autoTranslate;$('saveTranslation').onclick=saveTranslation;$('glossarySearch').oninput=e=>renderGlossary(e.target.value);$('contactSend').onclick=sendFeedback;$('authBtn').onclick=authClick;$('searchBtn').onclick=()=>loadArticles().catch(handleError);$('modalClose').onclick=()=>$('modal').classList.add('hidden');$('zoomIn').onclick=()=>{zoom=Math.min(2.5,zoom+.1);$('zoomLabel').textContent=Math.round(zoom*100)+'%';if(pdfURL)$('pdfStage').querySelector('iframe').src=pdfURL+'#zoom='+Math.round(zoom*100)};$('zoomOut').onclick=()=>{zoom=Math.max(.5,zoom-.1);$('zoomLabel').textContent=Math.round(zoom*100)+'%';if(pdfURL)$('pdfStage').querySelector('iframe').src=pdfURL+'#zoom='+Math.round(zoom*100)};$('progressBar').oninput=e=>{$('progressText').dataset.value=e.target.value;$('progressText').textContent=e.target.value+'%'};lunar();updateAuthUI()}
(async()=>{try{setup();if(token){try{user=(await api('/auth/me')).user}catch{token='';user=null}}updateAuthUI();await loadArticles();await loadSources();renderMyArticles();renderGlossary();const r=location.hash.slice(1);if(['home','contribute','sources','about'].includes(r))route(r)}catch(e){console.error(e);toast('Không kết nối được máy chủ Arcanum')}})();
