services:
  - type: web
    name: arcanum-archive-cloud
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: arcanum-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: MAX_UPLOAD_BYTES
        value: "262144000"

databases:
  - name: arcanum-db
    plan: free
    region: singapore
    databaseName: arcanum_db
    user: arcanum_user
