const path = require("path");
const express = require("express");
const bcrypt = require("bcryptjs");
const jwt = require("jsonwebtoken");
const multer = require("multer");
const { Pool } = require("pg");

const PORT = process.env.PORT || 10000;
const ROOT = __dirname;
const JWT_SECRET = process.env.JWT_SECRET || "CHANGE_ME_IN_RENDER";

if (!process.env.DATABASE_URL) console.warn("DATABASE_URL is not configured.");

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.DATABASE_URL ? { rejectUnauthorized: false } : false
});

const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: Number(process.env.MAX_UPLOAD_BYTES || 250 * 1024 * 1024) } });
const app = express();
app.use(express.json({ limit: "2mb" }));
app.use(express.urlencoded({ extended: true, limit: "2mb" }));
const q = (sql, params = []) => pool.query(sql, params);

const INIT_SQL = `
CREATE TABLE IF NOT EXISTS users (id BIGSERIAL PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,display_name TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('admin','editor','translator','member')),created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS files (id BIGSERIAL PRIMARY KEY,owner_id BIGINT REFERENCES users(id) ON DELETE SET NULL,name TEXT NOT NULL,mime_type TEXT NOT NULL,size_bytes BIGINT NOT NULL,data BYTEA NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS articles (id BIGSERIAL PRIMARY KEY,title TEXT NOT NULL,category TEXT NOT NULL,format TEXT NOT NULL DEFAULT 'Bài viết',body TEXT NOT NULL DEFAULT '',snippet TEXT NOT NULL DEFAULT '',tags JSONB NOT NULL DEFAULT '[]'::jsonb,citations TEXT NOT NULL DEFAULT '',visibility TEXT NOT NULL DEFAULT 'Công khai' CHECK (visibility IN ('Công khai','Chỉ thành viên','Lưu trữ cá nhân')),status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published')),author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,cover_file_id BIGINT REFERENCES files(id) ON DELETE SET NULL,version INTEGER NOT NULL DEFAULT 1,views INTEGER NOT NULL DEFAULT 0,saved INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS article_versions (id BIGSERIAL PRIMARY KEY,article_id BIGINT NOT NULL REFERENCES articles(id) ON DELETE CASCADE,version INTEGER NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL,citations TEXT NOT NULL DEFAULT '',editor_id BIGINT REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS bookmarks (user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,article_id BIGINT NOT NULL REFERENCES articles(id) ON DELETE CASCADE,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),PRIMARY KEY (user_id,article_id));
CREATE TABLE IF NOT EXISTS translations (id BIGSERIAL PRIMARY KEY,source_file_id BIGINT REFERENCES files(id) ON DELETE CASCADE,chapter TEXT NOT NULL DEFAULT '',source_text TEXT NOT NULL DEFAULT '',translated_text TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',progress INTEGER NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),editor_id BIGINT REFERENCES users(id) ON DELETE SET NULL,updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS feedback (id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL DEFAULT '',email TEXT NOT NULL DEFAULT '',message TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_articles_updated ON articles(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_articles_category ON articles(category);
CREATE INDEX IF NOT EXISTS idx_articles_status ON articles(status);
CREATE INDEX IF NOT EXISTS idx_files_owner ON files(owner_id);`;

function sign(user){return jwt.sign({id:user.id,email:user.email,role:user.role,name:user.display_name},JWT_SECRET,{expiresIn:"7d"});}
function auth(req,res,next){const h=req.headers.authorization||"";if(!h.startsWith("Bearer "))return res.status(401).json({error:"Unauthorized"});try{req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch(e){res.status(401).json({error:"Invalid or expired token"})}}
function role(...roles){return(req,res,next)=>roles.includes(req.user.role)?next():res.status(403).json({error:"Forbidden"})}

app.get("/api/health",async(req,res)=>{try{await q("SELECT 1");res.json({ok:true,database:true,service:"arcanum"})}catch(e){res.status(503).json({ok:false,database:false,error:e.message})}});
app.post("/api/auth/register",async(req,res)=>{const{email,password,displayName}=req.body||{};if(!email||!password||password.length<8)return res.status(400).json({error:"Email và mật khẩu tối thiểu 8 ký tự là bắt buộc"});try{if((await q("SELECT id FROM users WHERE lower(email)=lower($1)",[email])).rowCount)return res.status(409).json({error:"Email đã tồn tại"});const hash=await bcrypt.hash(password,12);const r=await q("INSERT INTO users(email,password_hash,display_name) VALUES($1,$2,$3) RETURNING id,email,display_name,role",[email.toLowerCase(),hash,displayName||email.split("@")[0]]);const u=r.rows[0];res.status(201).json({user:u,token:sign(u)})}catch(e){res.status(500).json({error:"Không thể tạo tài khoản",detail:e.message})}});
app.post("/api/auth/login",async(req,res)=>{const{email,password}=req.body||{};try{const r=await q("SELECT id,email,password_hash,display_name,role FROM users WHERE lower(email)=lower($1)",[email||""]);if(!r.rowCount||!(await bcrypt.compare(password||"",r.rows[0].password_hash)))return res.status(401).json({error:"Email hoặc mật khẩu không đúng"});const u=r.rows[0];delete u.password_hash;res.json({user:u,token:sign(u)})}catch(e){res.status(500).json({error:"Không thể đăng nhập",detail:e.message})}});
app.get("/api/auth/me",auth,async(req,res)=>{const r=await q("SELECT id,email,display_name,role,created_at FROM users WHERE id=$1",[req.user.id]);if(!r.rowCount)return res.status(404).json({error:"User not found"});res.json({user:r.rows[0]})});
app.get("/api/articles",async(req,res)=>{const{q:term,category,format,status="published"}=req.query,params=[],where=[];if(status){params.push(status);where.push(`a.status=$${params.length}`)}if(category){params.push(category);where.push(`a.category=$${params.length}`)}if(format){params.push(format);where.push(`a.format=$${params.length}`)}if(term){params.push("%"+term+"%");where.push(`(a.title ILIKE $${params.length} OR a.body ILIKE $${params.length} OR a.snippet ILIKE $${params.length})`)}try{const sql=`SELECT a.*,u.display_name author FROM articles a JOIN users u ON u.id=a.author_id ${where.length?"WHERE "+where.join(" AND "):""} ORDER BY a.updated_at DESC LIMIT 200`;res.json((await q(sql,params)).rows)}catch(e){res.status(500).json({error:e.message})}});
app.post("/api/articles",auth,async(req,res)=>{const d=req.body||{};if(!d.title||!d.category)return res.status(400).json({error:"Thiếu tiêu đề hoặc danh mục"});const c=await pool.connect();try{await c.query("BEGIN");const r=await c.query(`INSERT INTO articles(title,category,format,body,snippet,tags,citations,visibility,status,author_id,cover_file_id) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9,$10,$11) RETURNING *`,[d.title,d.category,d.format||"Bài viết",d.body||"",d.snippet||"",JSON.stringify(d.tags||[]),d.citations||"",d.visibility||"Công khai",d.status==="published"?"published":"draft",req.user.id,d.coverFileId||null]);const a=r.rows[0];await c.query("INSERT INTO article_versions(article_id,version,title,body,citations,editor_id) VALUES($1,1,$2,$3,$4,$5)",[a.id,a.title,a.body,a.citations,req.user.id]);await c.query("COMMIT");res.status(201).json(a)}catch(e){await c.query("ROLLBACK");res.status(500).json({error:e.message})}finally{c.release()}});
app.put("/api/articles/:id",auth,async(req,res)=>{const x=await q("SELECT * FROM articles WHERE id=$1",[req.params.id]);if(!x.rowCount)return res.status(404).json({error:"Not found"});const a=x.rows[0];if(a.author_id!==req.user.id&&!['admin','editor'].includes(req.user.role))return res.status(403).json({error:"Bạn không có quyền sửa bài này"});const d=req.body,v=a.version+1,r=await q(`UPDATE articles SET title=$1,category=$2,format=$3,body=$4,snippet=$5,tags=$6::jsonb,citations=$7,visibility=$8,status=$9,version=$10,cover_file_id=COALESCE($11,cover_file_id),updated_at=now() WHERE id=$12 RETURNING *`,[d.title||a.title,d.category||a.category,d.format||a.format,d.body??a.body,d.snippet??a.snippet,JSON.stringify(d.tags??a.tags),d.citations??a.citations,d.visibility||a.visibility,d.status==="published"?"published":"draft",v,d.coverFileId||null,a.id]);await q("INSERT INTO article_versions(article_id,version,title,body,citations,editor_id) VALUES($1,$2,$3,$4,$5,$6)",[a.id,v,r.rows[0].title,r.rows[0].body,r.rows[0].citations,req.user.id]);res.json(r.rows[0])});
app.get("/api/articles/:id/versions",auth,async(req,res)=>res.json((await q("SELECT * FROM article_versions WHERE article_id=$1 ORDER BY version DESC",[req.params.id])).rows));
app.post("/api/articles/:id/bookmark",auth,async(req,res)=>{await q("INSERT INTO bookmarks(user_id,article_id) VALUES($1,$2) ON CONFLICT DO NOTHING",[req.user.id,req.params.id]);await q("UPDATE articles SET saved=(SELECT count(*) FROM bookmarks WHERE article_id=$1) WHERE id=$1",[req.params.id]);res.json({ok:true})});
app.delete("/api/articles/:id/bookmark",auth,async(req,res)=>{await q("DELETE FROM bookmarks WHERE user_id=$1 AND article_id=$2",[req.user.id,req.params.id]);await q("UPDATE articles SET saved=(SELECT count(*) FROM bookmarks WHERE article_id=$1) WHERE id=$1",[req.params.id]);res.json({ok:true})});
app.post("/api/files",auth,upload.single("file"),async(req,res)=>{if(!req.file)return res.status(400).json({error:"Thiếu tệp"});if(!/^(image\/(png|jpeg|webp|gif)|application\/pdf)$/i.test(req.file.mimetype))return res.status(415).json({error:"Chỉ cho phép ảnh hoặc PDF"});const r=await q("INSERT INTO files(owner_id,name,mime_type,size_bytes,data) VALUES($1,$2,$3,$4,$5) RETURNING id,name,mime_type,size_bytes,created_at",[req.user.id,req.file.originalname,req.file.mimetype,req.file.size,req.file.buffer]);res.status(201).json(r.rows[0])});
app.get("/api/files/:id",auth,async(req,res)=>{const r=await q("SELECT name,mime_type,size_bytes,data FROM files WHERE id=$1",[req.params.id]);if(!r.rowCount)return res.status(404).end();const f=r.rows[0];res.setHeader("Content-Type",f.mime_type);res.setHeader("Content-Length",f.size_bytes);res.setHeader("Content-Disposition",`inline; filename*=UTF-8''${encodeURIComponent(f.name)}`);res.end(f.data)});
app.get("/api/files",auth,async(req,res)=>res.json((await q("SELECT id,name,mime_type,size_bytes,created_at FROM files WHERE owner_id=$1 ORDER BY created_at DESC",[req.user.id])).rows));
app.post("/api/translations",auth,async(req,res)=>{const d=req.body||{},r=await q(`INSERT INTO translations(source_file_id,chapter,source_text,translated_text,notes,progress,editor_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[d.sourceFileId||null,d.chapter||"",d.sourceText||"",d.translatedText||"",d.notes||"",Math.max(0,Math.min(100,Number(d.progress)||0)),req.user.id]);res.status(201).json(r.rows[0])});
app.put("/api/translations/:id",auth,async(req,res)=>{const d=req.body||{},r=await q(`UPDATE translations SET chapter=$1,source_text=$2,translated_text=$3,notes=$4,progress=$5,editor_id=$6,updated_at=now() WHERE id=$7 RETURNING *`,[d.chapter||"",d.sourceText||"",d.translatedText||"",d.notes||"",Math.max(0,Math.min(100,Number(d.progress)||0)),req.user.id,req.params.id]);res.json(r.rows[0]||null)});
app.post("/api/feedback",async(req,res)=>{const{name="",email="",message=""}=req.body||{};if(!message.trim())return res.status(400).json({error:"Thiếu nội dung"});const r=await q("INSERT INTO feedback(name,email,message) VALUES($1,$2,$3) RETURNING id,created_at",[name,email,message]);res.status(201).json(r.rows[0])});
app.get("/api/admin/users",auth,role("admin"),async(req,res)=>res.json((await q("SELECT id,email,display_name,role,created_at FROM users ORDER BY created_at DESC")).rows));
app.patch("/api/admin/users/:id/role",auth,role("admin"),async(req,res)=>{if(!["admin","editor","translator","member"].includes(req.body.role))return res.status(400).json({error:"Role không hợp lệ"});const r=await q("UPDATE users SET role=$1 WHERE id=$2 RETURNING id,email,display_name,role",[req.body.role,req.params.id]);res.json(r.rows[0]||null)});
app.use(express.static(ROOT));
app.use((req,res,next)=>{if(req.method==="GET"&&!req.path.startsWith("/api/"))return res.sendFile(path.join(ROOT,"index.html"));next()});

async function boot(){if(process.env.DATABASE_URL){await pool.query(INIT_SQL);console.log("Arcanum database schema ready")}app.listen(PORT,"0.0.0.0",()=>console.log(`Arcanum Cloud listening on ${PORT}`))}
boot().catch(err=>{console.error("Arcanum startup failed:",err);process.exit(1)});
