const path=require('path');const express=require('express');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const multer=require('multer');const {Pool}=require('pg');
const PORT=process.env.PORT||10000,ROOT=__dirname,JWT_SECRET=process.env.JWT_SECRET||'CHANGE_ME_IN_RENDER';
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:false});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:Number(process.env.MAX_UPLOAD_BYTES||250*1024*1024)}});const app=express();
app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:true,limit:'2mb'}));
const q=(s,p=[])=>pool.query(s,p);const sign=u=>jwt.sign({id:u.id,email:u.email,role:u.role,name:u.display_name},JWT_SECRET,{expiresIn:'7d'});
function auth(req,res,next){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'Unauthorized'});try{req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch(e){res.status(401).json({error:'Invalid or expired token'})}}
function role(...r){return(req,res,next)=>r.includes(req.user.role)?next():res.status(403).json({error:'Forbidden'})}
app.get('/api/health',async(req,res)=>{try{await q('SELECT 1');res.json({ok:true,database:true,service:'arcanum'})}catch(e){res.status(503).json({ok:false,database:false,error:e.message})}});
app.post('/api/auth/register',async(req,res)=>{const{email,password,displayName}=req.body||{};if(!email||!password||password.length<8)return res.status(400).json({error:'Email và mật khẩu tối thiểu 8 ký tự là bắt buộc'});try{if((await q('SELECT id FROM users WHERE lower(email)=lower($1)',[email])).rowCount)return res.status(409).json({error:'Email đã tồn tại'});const h=await bcrypt.hash(password,12),r=await q('INSERT INTO users(email,password_hash,display_name) VALUES($1,$2,$3) RETURNING id,email,display_name,role',[email.toLowerCase(),h,displayName||email.split('@')[0]]),u=r.rows[0];res.status(201).json({user:u,token:sign(u)})}catch(e){res.status(500).json({error:'Không thể tạo tài khoản'})}});
app.post('/api/auth/login',async(req,res)=>{const{email,password}=req.body||{};try{const r=await q('SELECT id,email,password_hash,display_name,role FROM users WHERE lower(email)=lower($1)',[email||'']);if(!r.rowCount||!(await bcrypt.compare(password||'',r.rows[0].password_hash)))return res.status(401).json({error:'Email hoặc mật khẩu không đúng'});const u=r.rows[0];delete u.password_hash;res.json({user:u,token:sign(u)})}catch(e){res.status(500).json({error:'Không thể đăng nhập'})}});
app.get('/api/auth/me',auth,async(req,res)=>{const r=await q('SELECT id,email,display_name,role,created_at FROM users WHERE id=$1',[req.user.id]);if(!r.rowCount)return res.status(404).json({error:'User not found'});res.json({user:r.rows[0]})});
app.get('/api/articles',async(req,res)=>{const{q:term,category,format,status='published'}=req.query,p=[],w=[];if(status){p.push(status);w.push(`a.status=$${p.length}`)}if(category){p.push(category);w.push(`a.category=$${p.length}`)}if(format){p.push(format);w.push(`a.format=$${p.length}`)}if(term){p.push('%'+term+'%');w.push(`(a.title ILIKE $${p.length} OR a.body ILIKE $${p.length} OR a.snippet ILIKE $${p.length})`)}try{res.json((await q(`SELECT a.*,u.display_name author FROM articles a JOIN users u ON u.id=a.author_id ${w.length?'WHERE '+w.join(' AND '):''} ORDER BY a.updated_at DESC LIMIT 200`,p)).rows)}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/articles',auth,async(req,res)=>{const d=req.body||{};if(!d.title||!d.category)return res.status(400).json({error:'Thiếu tiêu đề hoặc danh mục'});const c=await pool.connect();try{await c.query('BEGIN');const r=await c.query(`INSERT INTO articles(title,category,format,body,snippet,tags,citations,visibility,status,author_id,cover_file_id) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9,$10,$11) RETURNING *`,[d.title,d.category,d.format||'Bài viết',d.body||'',d.snippet||'',JSON.stringify(d.tags||[]),d.citations||'',d.visibility||'Công khai',d.status==='published'?'published':'draft',req.user.id,d.coverFileId||null]);const a=r.rows[0];await c.query('INSERT INTO article_versions(article_id,version,title,body,citations,editor_id) VALUES($1,1,$2,$3,$4,$5)',[a.id,a.title,a.body,a.citations,req.user.id]);await c.query('COMMIT');res.status(201).json(a)}catch(e){await c.query('ROLLBACK');res.status(500).json({error:e.message})}finally{c.release()}});
app.put('/api/articles/:id',auth,async(req,res)=>{const x=await q('SELECT * FROM articles WHERE id=$1',[req.params.id]);if(!x.rowCount)return res.status(404).json({error:'Not found'});const a=x.rows[0];if(a.author_id!==req.user.id&&!['admin','editor'].includes(req.user.role))return res.status(403).json({error:'Bạn không có quyền sửa bài này'});const d=req.body,v=a.version+1,r=await q(`UPDATE articles SET title=$1,category=$2,format=$3,body=$4,snippet=$5,tags=$6::jsonb,citations=$7,visibility=$8,status=$9,version=$10,cover_file_id=COALESCE($11,cover_file_id),updated_at=now() WHERE id=$12 RETURNING *`,[d.title||a.title,d.category||a.category,d.format||a.format,d.body??a.body,d.snippet??a.snippet,JSON.stringify(d.tags??a.tags),d.citations??a.citations,d.visibility||a.visibility,d.status==='published'?'published':'draft',v,d.coverFileId||null,a.id]);await q('INSERT INTO article_versions(article_id,version,title,body,citations,editor_id) VALUES($1,$2,$3,$4,$5,$6)',[a.id,v,r.rows[0].title,r.rows[0].body,r.rows[0].citations,req.user.id]);res.json(r.rows[0])});
app.get('/api/articles/:id/versions',auth,async(req,res)=>res.json((await q('SELECT * FROM article_versions WHERE article_id=$1 ORDER BY version DESC',[req.params.id])).rows));
app.post('/api/articles/:id/bookmark',auth,async(req,res)=>{await q('INSERT INTO bookmarks(user_id,article_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.user.id,req.params.id]);await q('UPDATE articles SET saved=(SELECT count(*) FROM bookmarks WHERE article_id=$1) WHERE id=$1',[req.params.id]);res.json({ok:true})});
app.post('/api/files',auth,upload.single('file'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'Thiếu tệp'});if(!/^(image\/(png|jpeg|webp|gif)|application\/pdf)$/i.test(req.file.mimetype))return res.status(415).json({error:'Chỉ cho phép ảnh hoặc PDF'});const r=await q('INSERT INTO files(owner_id,name,mime_type,size_bytes,data) VALUES($1,$2,$3,$4,$5) RETURNING id,name,mime_type,size_bytes,created_at',[req.user.id,req.file.originalname,req.file.mimetype,req.file.size,req.file.buffer]);res.status(201).json(r.rows[0])});
app.get('/api/files/:id',async(req,res)=>{const r=await q('SELECT name,mime_type,size_bytes,data FROM files WHERE id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).end();const f=r.rows[0];res.setHeader('Content-Type',f.mime_type);res.setHeader('Content-Length',f.size_bytes);res.setHeader('Content-Disposition',`inline; filename*=UTF-8''${encodeURIComponent(f.name)}`);res.end(f.data)});
app.get('/api/files',auth,async(req,res)=>res.json((await q('SELECT id,name,mime_type,size_bytes,created_at FROM files WHERE owner_id=$1 ORDER BY created_at DESC',[req.user.id])).rows));
app.post('/api/translations',auth,async(req,res)=>{const d=req.body||{},r=await q('INSERT INTO translations(source_file_id,chapter,source_text,translated_text,notes,progress,editor_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[d.sourceFileId||null,d.chapter||'',d.sourceText||'',d.translatedText||'',d.notes||'',Math.max(0,Math.min(100,Number(d.progress)||0)),req.user.id]);res.status(201).json(r.rows[0])});
app.post('/api/feedback',async(req,res)=>{const{name='',email='',message=''}=req.body||{};if(!message.trim())return res.status(400).json({error:'Thiếu nội dung'});const r=await q('INSERT INTO feedback(name,email,message) VALUES($1,$2,$3) RETURNING id,created_at',[name,email,message]);res.status(201).json(r.rows[0])});
app.get('/api/admin/users',auth,role('admin'),async(req,res)=>res.json((await q('SELECT id,email,display_name,role,created_at FROM users ORDER BY created_at DESC')).rows));
app.patch('/api/admin/users/:id/role',auth,role('admin'),async(req,res)=>{if(!['admin','editor','translator','member'].includes(req.body.role))return res.status(400).json({error:'Role không hợp lệ'});const r=await q('UPDATE users SET role=$1 WHERE id=$2 RETURNING id,email,display_name,role',[req.body.role,req.params.id]);res.json(r.rows[0]||null)});
app.use(express.static(ROOT));app.use((req,res,next)=>{if(req.method==='GET'&&!req.path.startsWith('/api/'))return res.sendFile(path.join(ROOT,'index.html'));next()});
app.listen(PORT,'0.0.0.0',()=>console.log(`Arcanum Cloud listening on ${PORT}`));
